In [1]:
import numpy as np
import pandas as pd
import pickle

In [2]:
df_full_plate_pattern = pd.read_csv('full_dataset_v2_path_plate_groups_only_20190812.csv', index_col=0)

In [3]:
df_full_plate_pattern['test'] = df_full_plate_pattern['path'].apply(lambda x: x.startswith('test'))

In [4]:
testpath2name = lambda x: x.split('/')[1]+'_'+x.split('/')[2][-1]+'_'+x.split('/')[-1]

In [5]:
df_full_plate_pattern['name'] = df_full_plate_pattern.path.apply(testpath2name)

In [6]:
df_full_plate_pattern['exp'] = df_full_plate_pattern.path.apply(lambda x: x.split('/')[1])

In [7]:
df_full_plate_pattern[df_full_plate_pattern['test'] == True].head()

path  plate_pattern  test               name  \
0  test/HEPG2-08/Plate1/B03_s1              3  True  HEPG2-08_1_B03_s1   
1  test/HEPG2-08/Plate1/B04_s1              3  True  HEPG2-08_1_B04_s1   
2  test/HEPG2-08/Plate1/B05_s1              3  True  HEPG2-08_1_B05_s1   
3  test/HEPG2-08/Plate1/B06_s1              3  True  HEPG2-08_1_B06_s1   
4  test/HEPG2-08/Plate1/B07_s1              3  True  HEPG2-08_1_B07_s1   

        exp  
0  HEPG2-08  
1  HEPG2-08  
2  HEPG2-08  
3  HEPG2-08  
4  HEPG2-08

In [8]:
df_full_plate_pattern[df_full_plate_pattern['exp'] == 'RPE-08'].head()

path  plate_pattern  test             name     exp
13275  test/RPE-08/Plate1/B03_s1              2  True  RPE-08_1_B03_s1  RPE-08
13276  test/RPE-08/Plate1/B04_s1              2  True  RPE-08_1_B04_s1  RPE-08
13277  test/RPE-08/Plate1/B05_s1              2  True  RPE-08_1_B05_s1  RPE-08
13278  test/RPE-08/Plate1/B06_s1              2  True  RPE-08_1_B06_s1  RPE-08
13279  test/RPE-08/Plate1/B07_s1              2  True  RPE-08_1_B07_s1  RPE-08

In [9]:
name2pgint = dict(zip(df_full_plate_pattern.name.values, 
                      df_full_plate_pattern.plate_pattern.values))

In [10]:
testpath = 'test/RPE-08/Plate1/B06_s1'

In [11]:
testname = testpath[5:13]+'_'+testpath[19]+'_'+testpath[21:]

In [12]:
testname = testpath.split('/')[1]+'_'+testpath.split('/')[2][-1]+'_'+testpath.split('/')[-1]

In [13]:
name2pgint[testname]

2

In [14]:
names2exp = lambda x: x.split('_')[0]

In [15]:
names2site = lambda x: x[:-3]

In [16]:
names2s = lambda x: x.split('_')[-1]

In [20]:
preds_names = []
preds_test_full = []
dist_test_full = []
for pg in range(4):
    with open('pred/preds_test_pg'+str(pg)+'_names.txt', 'rb') as fp:   # Unpickling
        preds_names.append(pickle.load(fp))
    
    preds_test_full.append(np.load('pred/preds_test_pg'+str(pg)+'_full.npy'))
    dist_test_full.append(np.load('pred/dist_test_pg'+str(pg)+'_full.npy'))

In [21]:
preds_names = preds_names[0]+preds_names[1]+preds_names[2]+preds_names[3]

In [22]:
preds_test_full = np.concatenate(preds_test_full)
dist_test_full = np.concatenate(dist_test_full)

In [23]:
len(preds_names), preds_test_full.shape, dist_test_full.shape

(39794, (39794, 5), (39794, 5))

In [24]:
#pg = 0

In [25]:
#with open('pred/preds_test_pg'+str(pg)+'_names.txt', 'rb') as fp:   # Unpickling
#    preds_names = pickle.load(fp)

In [26]:
#preds_names

In [27]:
df = pd.DataFrame({'id_code_site': preds_names})#, 'sirna': preds_test, 'cossim': dist_test})

In [28]:
df['site'] = df['id_code_site'].apply(names2site)

In [29]:
df['s'] = df['id_code_site'].apply(names2s)

In [30]:
df['exp'] = df['id_code_site'].apply(names2exp)

In [31]:
df['pg'] = df['id_code_site'].apply(lambda x: name2pgint[x])

In [32]:
df.head()

id_code_site            site   s       exp  pg
0  HEPG2-08_2_B03_s1  HEPG2-08_2_B03  s1  HEPG2-08   0
1  HEPG2-08_2_B04_s1  HEPG2-08_2_B04  s1  HEPG2-08   0
2  HEPG2-08_2_B05_s1  HEPG2-08_2_B05  s1  HEPG2-08   0
3  HEPG2-08_2_B06_s1  HEPG2-08_2_B06  s1  HEPG2-08   0
4  HEPG2-08_2_B07_s1  HEPG2-08_2_B07  s1  HEPG2-08   0

In [33]:
#preds_test_full = np.load('pred/preds_test_pg'+str(pg)+'_full.npy')
#dist_test_full = np.load('pred/dist_test_pg'+str(pg)+'_full.npy')

In [34]:
preds_test_full

array([[341, 341, 341, 341, 341],
       [392, 392, 392, 392, 392],
       [411, 411, 411, 411, 411],
       ...,
       [316, 316, 316, 316, 316],
       [964, 964, 964, 964, 964],
       [316, 316, 316, 316, 316]])

In [35]:
dist_test_full

array([[0.8840368 , 0.87920463, 0.8776487 , 0.87199044, 0.8576728 ],
       [0.5957595 , 0.5956082 , 0.5873282 , 0.5854583 , 0.5814376 ],
       [0.8891903 , 0.888553  , 0.8879391 , 0.88784695, 0.8873372 ],
       ...,
       [0.9605947 , 0.9502472 , 0.94774413, 0.9468522 , 0.94632053],
       [0.952185  , 0.9508761 , 0.94766444, 0.9467374 , 0.9464259 ],
       [0.84018993, 0.83900803, 0.8365338 , 0.8345395 , 0.8323056 ]],
      dtype=float32)

In [36]:
dist_test_full[:,0]

array([0.8840368 , 0.5957595 , 0.8891903 , ..., 0.9605947 , 0.952185  ,
       0.84018993], dtype=float32)

In [37]:
df_pred = pd.DataFrame({'sirna': preds_test_full[:,0], 'cossim': dist_test_full[:,0]})

In [38]:
df_pred.head()

sirna    cossim
0    341  0.884037
1    392  0.595760
2    411  0.889190
3     26  0.706556
4    172  0.836110

In [39]:
df.head()

id_code_site            site   s       exp  pg
0  HEPG2-08_2_B03_s1  HEPG2-08_2_B03  s1  HEPG2-08   0
1  HEPG2-08_2_B04_s1  HEPG2-08_2_B04  s1  HEPG2-08   0
2  HEPG2-08_2_B05_s1  HEPG2-08_2_B05  s1  HEPG2-08   0
3  HEPG2-08_2_B06_s1  HEPG2-08_2_B06  s1  HEPG2-08   0
4  HEPG2-08_2_B07_s1  HEPG2-08_2_B07  s1  HEPG2-08   0

In [40]:
df_full = pd.concat((df, df_pred), axis=1)

In [41]:
df_full.head()

id_code_site            site   s       exp  pg  sirna    cossim
0  HEPG2-08_2_B03_s1  HEPG2-08_2_B03  s1  HEPG2-08   0    341  0.884037
1  HEPG2-08_2_B04_s1  HEPG2-08_2_B04  s1  HEPG2-08   0    392  0.595760
2  HEPG2-08_2_B05_s1  HEPG2-08_2_B05  s1  HEPG2-08   0    411  0.889190
3  HEPG2-08_2_B06_s1  HEPG2-08_2_B06  s1  HEPG2-08   0     26  0.706556
4  HEPG2-08_2_B07_s1  HEPG2-08_2_B07  s1  HEPG2-08   0    172  0.836110

In [42]:
df_full.sirna.max()

1107

In [43]:
df_full.sort_values('cossim', ascending=False).head()

id_code_site            site   s       exp  pg  sirna    cossim
7148   HUVEC-20_4_M20_s2  HUVEC-20_4_M20  s2  HUVEC-20   0     33  0.999844
26382  HUVEC-18_3_H10_s2  HUVEC-18_3_H10  s2  HUVEC-18   2    491  0.999814
17030  HUVEC-20_1_J10_s2  HUVEC-20_1_J10  s2  HUVEC-20   1      2  0.999810
37383  HUVEC-22_4_E13_s2  HUVEC-22_4_E13  s2  HUVEC-22   3   1001  0.999802
11721  HUVEC-19_1_G07_s1  HUVEC-19_1_G07  s1  HUVEC-19   1   1024  0.999801

In [61]:
df_full.groupby('pg').sirna.nunique()

pg
0    277
1    277
2    277
3    277
Name: sirna, dtype: int64

In [66]:
df_full.exp.unique()

array(['HEPG2-08', 'HEPG2-09', 'HEPG2-10', 'HEPG2-11', 'HUVEC-17',
       'HUVEC-18', 'HUVEC-19', 'HUVEC-20', 'HUVEC-21', 'HUVEC-22',
       'HUVEC-23', 'HUVEC-24', 'RPE-08', 'RPE-09', 'RPE-10', 'RPE-11',
       'U2OS-04', 'U2OS-05'], dtype=object)

In [71]:
for e in df_full.exp.unique():
    print(e)
    print(df_full[df_full['exp'] == e].groupby('pg').sirna.nunique())
    print('---')

HEPG2-08
pg
0    179
1    197
2    193
3    206
Name: sirna, dtype: int64
---
HEPG2-09
pg
0    141
1    168
2    202
3    160
Name: sirna, dtype: int64
---
HEPG2-10
pg
0    213
1    219
2    213
3    211
Name: sirna, dtype: int64
---
HEPG2-11
pg
0    218
1    216
2    225
3    217
Name: sirna, dtype: int64
---
HUVEC-17
pg
0    243
1    248
2    251
3    244
Name: sirna, dtype: int64
---
HUVEC-18
pg
0    247
1    239
2    243
3    215
Name: sirna, dtype: int64
---
HUVEC-19
pg
0    242
1    250
2    247
3    245
Name: sirna, dtype: int64
---
HUVEC-20
pg
0    270
1    273
2    273
3    274
Name: sirna, dtype: int64
---
HUVEC-21
pg
0    215
1    228
2    231
3    224
Name: sirna, dtype: int64
---
HUVEC-22
pg
0    253
1    262
2    267
3    264
Name: sirna, dtype: int64
---
HUVEC-23
pg
0    229
1    248
2    258
3    248
Name: sirna, dtype: int64
---
HUVEC-24
pg
0    244
1    245
2    254
3    249
Name: sirna, dtype: int64
---
RPE-08
pg
0    199
1    199
2    178
3    214
Name: sirna, dtype

In [74]:
df_full[df_full['exp'] == 'U2OS-04'].sort_values('cossim', ascending=False).head()

id_code_site           site   s      exp  pg  sirna    cossim  \
14601  U2OS-04_1_M09_s1  U2OS-04_1_M09  s1  U2OS-04   1    988  0.991822   
24536  U2OS-04_2_L21_s1  U2OS-04_2_L21  s1  U2OS-04   2    554  0.987816   
14614  U2OS-04_1_N04_s1  U2OS-04_1_N04  s1  U2OS-04   1    130  0.985088   
29390  U2OS-04_2_F20_s2  U2OS-04_2_F20  s2  U2OS-04   2    554  0.982192   
39504  U2OS-04_3_O08_s2  U2OS-04_3_O08  s2  U2OS-04   3    634  0.981648   

             id_code  
14601  U2OS-04_1_M09  
24536  U2OS-04_2_L21  
14614  U2OS-04_1_N04  
29390  U2OS-04_2_F20  
39504  U2OS-04_3_O08

In [64]:
#df_full.groupby('exp').sirna.unique()

In [47]:
df_full.groupby('exp').sirna.nunique()

exp
HEPG2-08     775
HEPG2-09     671
HEPG2-10     856
HEPG2-11     876
HUVEC-17     986
HUVEC-18     944
HUVEC-19     984
HUVEC-20    1090
HUVEC-21     898
HUVEC-22    1046
HUVEC-23     983
HUVEC-24     992
RPE-08       790
RPE-09       900
RPE-10       923
RPE-11       973
U2OS-04      317
U2OS-05      495
Name: sirna, dtype: int64

In [193]:
#df_full[df_full['pg'] == 0].groupby('sirna').sirna.nunique().max()

In [50]:
df_full.sort_values('cossim', ascending=False).head()

id_code_site            site   s       exp  pg  sirna    cossim
7148   HUVEC-20_4_M20_s2  HUVEC-20_4_M20  s2  HUVEC-20   0     33  0.999844
26382  HUVEC-18_3_H10_s2  HUVEC-18_3_H10  s2  HUVEC-18   2    491  0.999814
17030  HUVEC-20_1_J10_s2  HUVEC-20_1_J10  s2  HUVEC-20   1      2  0.999810
37383  HUVEC-22_4_E13_s2  HUVEC-22_4_E13  s2  HUVEC-22   3   1001  0.999802
11721  HUVEC-19_1_G07_s1  HUVEC-19_1_G07  s1  HUVEC-19   1   1024  0.999801

In [54]:
# get id_code without site
df_full['id_code'] = df_full['id_code_site'].apply(lambda x: x[:-3])

In [55]:
# get row indices with highest cosine similiarity
idx = []
for i, r in enumerate(df_full.sort_values('id_code').iterrows()):
    #print(r)
    #print('i: ',i)
    #print('idx: ',r[0])
    #print(r[1]['cossim'])
    if i % 2:
        # distance from row 2 is 
        if dist < r[1]['cossim']:
            idx.append(r[0])
        else:
            idx.append(idx_row_before)
    else:
        # save dist from row 1 for comparison in next iteration
        dist = r[1]['cossim']
        idx_row_before = r[0]

In [56]:
idx[:5]

[29848, 34822, 29850, 29851, 34825]

In [58]:
df_full.sort_values('id_code').head(10)

id_code_site            site   s       exp  pg  sirna    cossim  \
34821  HEPG2-08_1_B03_s2  HEPG2-08_1_B03  s2  HEPG2-08   3    855  0.782045   
29848  HEPG2-08_1_B03_s1  HEPG2-08_1_B03  s1  HEPG2-08   3    855  0.935911   
29849  HEPG2-08_1_B04_s1  HEPG2-08_1_B04  s1  HEPG2-08   3    756  0.575508   
34822  HEPG2-08_1_B04_s2  HEPG2-08_1_B04  s2  HEPG2-08   3    358  0.666506   
29850  HEPG2-08_1_B05_s1  HEPG2-08_1_B05  s1  HEPG2-08   3     85  0.571876   
34823  HEPG2-08_1_B05_s2  HEPG2-08_1_B05  s2  HEPG2-08   3     79  0.554588   
34824  HEPG2-08_1_B06_s2  HEPG2-08_1_B06  s2  HEPG2-08   3    249  0.727727   
29851  HEPG2-08_1_B06_s1  HEPG2-08_1_B06  s1  HEPG2-08   3    280  0.849810   
29852  HEPG2-08_1_B07_s1  HEPG2-08_1_B07  s1  HEPG2-08   3    321  0.707861   
34825  HEPG2-08_1_B07_s2  HEPG2-08_1_B07  s2  HEPG2-08   3    261  0.897638   

              id_code  
34821  HEPG2-08_1_B03  
29848  HEPG2-08_1_B03  
29849  HEPG2-08_1_B04  
34822  HEPG2-08_1_B04  
29850  HEPG2-08_1_B05  
34823  HEPG2-08_1_B05  
34824  HEPG2-08_1_B06  
29851  HEPG2-08_1_B06  
29852  HEPG2-08_1_B07  
34825  HEPG2-08_1_B07

In [60]:
df_full.loc[idx].head()

id_code_site            site   s       exp  pg  sirna    cossim  \
29848  HEPG2-08_1_B03_s1  HEPG2-08_1_B03  s1  HEPG2-08   3    855  0.935911   
34822  HEPG2-08_1_B04_s2  HEPG2-08_1_B04  s2  HEPG2-08   3    358  0.666506   
29850  HEPG2-08_1_B05_s1  HEPG2-08_1_B05  s1  HEPG2-08   3     85  0.571876   
29851  HEPG2-08_1_B06_s1  HEPG2-08_1_B06  s1  HEPG2-08   3    280  0.849810   
34825  HEPG2-08_1_B07_s2  HEPG2-08_1_B07  s2  HEPG2-08   3    261  0.897638   

              id_code  
29848  HEPG2-08_1_B03  
34822  HEPG2-08_1_B04  
29850  HEPG2-08_1_B05  
29851  HEPG2-08_1_B06  
34825  HEPG2-08_1_B07